name: learn-github-actions
run-name: ${{ github.actor}} is learning Github Actions
on:
  push:
    branches:
      - master
jobs:
  checks-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo Hello, world!
      - run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - run: |
          echo "import sys" > myscript.py
          echo "print(sys.argv[1].split("_"))" >> myscript.py
      - run: python myscript.py ${{ secrets.SECRET_CHECK }}
