name: learn-github-actions
run-name: ${{ github.actor}} is learning Github Actions
on:
  push:
    branches:
      - master
jobs:
  checks-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run a one-line script
        run: echo Hello, world!
      - name: run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: check Secret Value
        run: |
          echo ${{ secrets.SECRET_CHECK }}
