name: Start EC2 Instance
run-name: Starting EC2 Instance
on:
  push:
    branches:
      - master
jobs:
  starts-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Start AWS EC2
        run: |
          aws ec2 start-instances --instance-ids ${{ secrets.AWS_EC2_INSTANCE_ID }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
